name: Test, Build and Deploy
on:
  push:
    branches: ['main']
env:
  NODE_ENV: production
  FAST_REFRESH: false
  CI: false
permissions:
  contents: write
  pull-requests: write
jobs:
  CICD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: |
          npm install
          npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: example
          branch: gh-pages
