name: Node.js CI

on: [push, pull_request]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18"
      - run: yarn install
      - run: yarn test
      - run: yarn build
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
