name: NPM Package Publish
on: workflow_dispatch
env:
    CI: false
    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
permissions:
    contents: write
    pull-requests: write
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@qiming-liu'
      - run: |
          npm install
          npm run publish
          